In [ ]:
import pandas as pd
import random

random.seed(42)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/AML_Project"

In [ ]:
cities_df = pd.read_csv("cities.csv")

cities_df.head()

   city_id       city        state  latitude  longitude  population country
0  CITY001      Delhi        Delhi   28.6139    77.2090    33000000   India
1  CITY002     Mumbai  Maharashtra   19.0760    72.8777    21000000   India
2  CITY003  Bengaluru    Karnataka   12.9716    77.5946    14000000   India
3  CITY004    Chennai   Tamil Nadu   13.0827    80.2707    11000000   India
4  CITY005  Hyderabad    Telangana   17.3850    78.4867    10500000   India

In [ ]:
banks = [
    "State Bank of India",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Punjab National Bank",
    "Bank of Baroda",
    "Canara Bank",
    "Union Bank",
    "Indian Bank",
    "Kotak Mahindra Bank"
]

In [ ]:
num_atms = 200

atms = []

for i in range(1, num_atms + 1):

    city = cities_df.sample(1).iloc[0]

    # Slight random offset around city center
    latitude = city["latitude"] + random.uniform(-0.05, 0.05)
    longitude = city["longitude"] + random.uniform(-0.05, 0.05)

    atm_type = random.choices(
        ["ATM", "Branch"],
        weights=[80,20]
    )[0]

    bank = random.choice(banks)

    atms.append({

        "atm_id": f"ATM{i:04d}",

        "bank_name": bank,

        "atm_type": atm_type,

        "city_id": city["city_id"],

        "city": city["city"],

        "state": city["state"],

        "country": city["country"],

        "latitude": round(latitude,6),

        "longitude": round(longitude,6)

    })

In [ ]:
atms_df = pd.DataFrame(atms)

atms_df.head()

,atm_id,bank_name,atm_type,city_id,city,state,country,latitude,longitude
0,ATM0001,Axis Bank,ATM,CITY002,Mumbai,Maharashtra,India,19.089943,72.830201
1,ATM0002,Indian Bank,ATM,CITY012,Kanpur,Uttar Pradesh,India,26.413854,80.292150
2,ATM0003,Axis Bank,ATM,CITY019,Coimbatore,Tamil Nadu,India,10.975494,76.947992
3,ATM0004,Indian Bank,ATM,CITY017,Chandigarh,Chandigarh,India,30.706566,76.789602
4,ATM0005,State Bank of India,ATM,CITY015,Bhopal,Madhya Pradesh,India,23.251852,77.407521

In [ ]:
atms_df.to_csv(
    f"{PROJECT_PATH}/dataset/atms.csv",
    index=False
)

print("ATM Dataset Generated Successfully!")

print()

print(atms_df.head())

print()

print("Total ATMs :", len(atms_df))

print()

print(atms_df["atm_type"].value_counts())

ATM Dataset Generated Successfully!

    atm_id            bank_name atm_type  city_id        city           state  \
0  ATM0001            Axis Bank      ATM  CITY002      Mumbai     Maharashtra
1  ATM0002          Indian Bank      ATM  CITY012      Kanpur   Uttar Pradesh
2  ATM0003            Axis Bank      ATM  CITY019  Coimbatore      Tamil Nadu
3  ATM0004          Indian Bank      ATM  CITY017  Chandigarh      Chandigarh
4  ATM0005  State Bank of India      ATM  CITY015      Bhopal  Madhya Pradesh

  country   latitude  longitude
0   India  19.089943  72.830201
1   India  26.413854  80.292150
2   India  10.975494  76.947992
3   India  30.706566  76.789602
4   India  23.251852  77.407521

Total ATMs : 200

atm_type
ATM       162
Branch     38
Name: count, dtype: int64