In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import random
import numpy as np

random.seed(42)
np.random.seed(42)

PROJECT_PATH = "/content/drive/MyDrive/AML_Project"

Mounted at /content/drive

In [ ]:
cities = pd.read_csv(f"{PROJECT_PATH}/dataset/cities.csv")

cities.head()

   city_id       city        state  latitude  longitude  population country
0  CITY001      Delhi        Delhi   28.6139    77.2090    33000000   India
1  CITY002     Mumbai  Maharashtra   19.0760    72.8777    21000000   India
2  CITY003  Bengaluru    Karnataka   12.9716    77.5946    14000000   India
3  CITY004    Chennai   Tamil Nadu   13.0827    80.2707    11000000   India
4  CITY005  Hyderabad    Telangana   17.3850    78.4867    10500000   India

In [ ]:
merchant_categories = {

    "Shopping":[
        "Amazon",
        "Flipkart",
        "Myntra",
        "Reliance Retail",
        "DMart",
        "Croma"
    ],

    "Food":[
        "Swiggy",
        "Zomato",
        "Dominos",
        "Pizza Hut",
        "KFC",
        "McDonalds"
    ],

    "Fuel":[
        "Indian Oil",
        "HP Petrol",
        "Bharat Petroleum",
        "Shell"
    ],

    "Bills":[
        "Electricity Board",
        "Water Department",
        "Gas Agency",
        "Internet Provider",
        "Mobile Recharge"
    ],

    "Healthcare":[
        "Apollo Hospital",
        "Fortis",
        "Max Healthcare",
        "Pharmacy"
    ],

    "Travel":[
        "IRCTC",
        "Uber",
        "Ola",
        "IndiGo",
        "Air India"
    ],

    "Entertainment":[
        "Netflix",
        "Amazon Prime",
        "BookMyShow",
        "PVR"
    ]
}

In [ ]:
merchants = []

merchant_counter = 1

for category, names in merchant_categories.items():

    for city in cities.itertuples():

        # Every city gets 2–5 merchants from every category
        num = random.randint(2,5)

        for _ in range(num):

            merchant_name = random.choice(names)

            merchants.append({

                "merchant_id":f"MER{merchant_counter:05d}",

                "merchant_name":merchant_name,

                "category":category,

                "city_id":city.city_id,

                "city":city.city,

                "state":city.state,

                "country":city.country,

                "latitude":round(
                    city.latitude +
                    random.uniform(-0.04,0.04),
                    6
                ),

                "longitude":round(
                    city.longitude +
                    random.uniform(-0.04,0.04),
                    6
                )

            })

            merchant_counter += 1

In [ ]:
merchants = pd.DataFrame(merchants)

print("Total Merchants:",len(merchants))

merchants.head()

Total Merchants: 501

,merchant_id,merchant_name,category,city_id,city,state,country,latitude,longitude
0,MER00001,Amazon,Shopping,CITY001,Delhi,Delhi,India,28.633224,77.188591
1,MER00002,Flipkart,Shopping,CITY001,Delhi,Delhi,India,28.632818,77.223136
2,MER00003,DMart,Shopping,CITY002,Mumbai,Maharashtra,India,19.069754,72.840084
3,MER00004,Flipkart,Shopping,CITY002,Mumbai,Maharashtra,India,19.054613,72.885861
4,MER00005,Croma,Shopping,CITY003,Bengaluru,Karnataka,India,12.983591,77.598195

In [ ]:
merchants.to_csv(
    f"{PROJECT_PATH}/dataset/merchants.csv",
    index=False
)

print("Merchants Dataset Saved Successfully")

Merchants Dataset Saved Successfully